#!/usr/bin/env bash


# 3k model
#prefered_resolution="2880x1800@120.000"
#prefered_resolution="2880x1800@120.00029754638672"
prefered_resolution="2880x1800@60.000701904296875"
#ui_scale=1.7475727796554565 # 1.75
ui_scale=1.5 # 1.5
# y offset = height of resolution / ui_scale (1800/1.7475... = 1030), but better to check via bustle (recording session bus, you are interested in org.gnome.Mutter.DisplayConfig.ApplyMonitorsConfig call. start recording and configure display in gnome display settings)
#y_offset=1030
#y_offset=1200
y_offset=2400
backlight=card1-eDP-2-backlight

# 1080p model
#prefered_resolution="1920x1200@60.003"
#backlight=card1-eDP-2-backlight
#ui_scale=1
#y_offset=1200

suenv() {
  sudo /usr/bin/env "$@"
}

external_display_connected() {
  [ "$(gnome-monitor-config list|grep display-name|grep -v 'Built-in display'|wc -l)" != "0" ]
}

active_external_displays() {
  gnome-monitor-config list|grep -vE 'eDP-[12]'|sed -nE 's/Monitor \[ (.+) \] ON/\1/p'
}

# mv

status_internal() {
  internal_monitors="$(gnome-monitor-config list|grep -E "Monitor \\[ eDP-. \\] ON")"
  case "$(echo "$internal_monitors"|grep -v -E "^$"|wc -l)" in
    0) echo "none" ;;
    1) case "$(echo "$internal_monitors"|grep ON)" in
         "Monitor [ eDP-1 ] ON") echo top ;;
         "Monitor [ eDP-2 ] ON") echo bottom ;;
       esac ;;
    2) echo "both" ;;
  esac
}

set_displays_external() {
  sleep 2
  if ! external_display_connected; then 
    set_displays_normal
  fi
}

set_displays_external_kbd() {
  sleep 2
  if ! external_display_connected; then 
    set_displays_normal_kbd $1
  fi
}

set_displays() {
  echo "set_displays $1 $(status_internal)" >>/tmp/duo.log    
  if [[ $1 != $(status_internal) ]]; then   
    set_displays_internal $1
    sleep 1
  fi
  set_tablet_mapping
}

set_displays_internal() {
  case "$1" in
    top)
      gnome-monitor-config set \
        -LpM eDP-1 -m $prefered_resolution  -s $ui_scale -x 0 -y 0
      ;;
    both)
      gnome-monitor-config set \
        -LpM eDP-1 -m $prefered_resolution -s $ui_scale -x 0 -y 0 \
        -LM  eDP-2 -m $prefered_resolution -s $ui_scale -x 0 -y $y_offset
      ;;
    bottom)
      gnome-monitor-config set \
        -LpM eDP-2 -m $prefered_resolution -s $ui_scale -x 0 -y 0
      ;;
    left-up)
      gnome-monitor-config set \
        -LpM eDP-2 -m $prefered_resolution -s $ui_scale -t left  -x 0         -y 0 \
        -LM  eDP-1 -m $prefered_resolution -s $ui_scale -t left  -x $y_offset -y 0
      ;;
    right-up)
      gnome-monitor-config set \
        -LM  eDP-1 -m $prefered_resolution -s $ui_scale -t right -x 0         -y 0 \
        -LpM eDP-2 -m $prefered_resolution -s $ui_scale -t right -x $y_offset -y 0
      ;;
  esac
}

set_displays_normal() {
  set_displays_normal_kbd kbd_connected
}

set_displays_normal_kbd() {
  #if lsusb|grep 0b05:1b2c ; then
  #if kbd_connected ; then
  if $1 ; then
    set_displays top
  else
    set_displays both
  fi
}

set_tablet_mapping() {
  case $(status_internal) in
  top)
    #echo "top"
    #xinput set-prop 'ELAN9008:00 04F3:425B' --type=float "Coordinate Transformation Matrix" 1 0 0 0 1 0 0 0 1
    xinput map-to-output 'pointer:ELAN9008:00 04F3:425B' eDP-1
    ;;
  both)
    #echo "both"
    #xinput set-prop 'ELAN9008:00 04F3:425B' --type=float "Coordinate Transformation Matrix" 1 0 0 0 0.5 0 0 0 1
    #xinput set-prop 'ELAN9009:00 04F3:425A' --type=float "Coordinate Transformation Matrix" 1 0 0 0 0.5 0.5 0 0 1
    xinput map-to-output 'pointer:ELAN9008:00 04F3:425B' eDP-1
    xinput map-to-output 'pointer:ELAN9009:00 04F3:425A' eDP-2
    ;;
  esac
}

sync_backlight() {
  cat "/sys/class/backlight/intel_backlight/brightness" |
    suenv tee /sys/class/backlight/$backlight/brightness
}

kbd_connected() {
  echo "0x00050051" | suenv tee "/sys/kernel/debug/asus-nb-wmi/dev_id"
  [ "$(suenv cat '/sys/kernel/debug/asus-nb-wmi/dsts'|cut -d' ' -f3)" == "0x10000" ]
}

echo "$(date) $1" >>/tmp/duo.log

case "$1" in
  set-displays)
    set_displays_external
    ;;
  normal|bottom-up)
    set_displays_normal
    ;;
  top|both|bottom)
    set_displays $1
    ;;
  left-up|right-up)
    set_displays $1
    ;;
  status-internal)
    status_internal
    ;;
  status)
    (
      active_external_displays
    )|grep -vE "^$"|sed -z "s/\n/+/g"
    status_internal
    ;;
  toggle)
    if gnome-monitor-config list | grep OFF > /dev/null; then
      set_displays both
    else
      set_displays top
    fi
    ;;
  set-tablet-mapping-gnome)
    for type in tablets touchscreens; do
      dconf write "/org/gnome/desktop/peripherals/${type}/04f3:425b/output" \
        "['SDC', '0x419d', '0x00000000', 'eDP-1']"
      dconf write "/org/gnome/desktop/peripherals/${type}/04f3:425a/output" \
        "['SDC', '0x419d', '0x00000000', 'eDP-2']"
    done
    ;;
  set-tablet-mapping)
    set_tablet_mapping
    ;;
  bat-limit)
    echo "${2:-80}" | suenv tee /sys/class/power_supply/BAT0/charge_control_end_threshold
    ;;
  sync-backlight)
    sync_backlight
    ;;
  watch-backlight)
    sync_backlight
    while inotifywait -e modify /sys/class/backlight/intel_backlight/brightness ; do
       sync_backlight
    done
    ;;
  watch-rotation)
    monitor-sensor --accel |
      stdbuf -oL grep orientation |
      stdbuf -oL cut -d: -f2 |
      stdbuf -oL sed 's/[ )]//g' |
      xargs -I '{}' duo '{}'
    ;;
  watch-sw-tablet-mode)
    # https://unix.stackexchange.com/questions/428399/how-can-i-run-a-shell-script-on-input-device-event
    device='/dev/input/by-path/platform-asus-nb-wmi-event'
    #event_dock='*code 4 (MSC_SCAN), value 5e*'
    event_tablet_on='*code 1 (SW_TABLET_MODE), value 1'
    event_tablet_off='*code 1 (SW_TABLET_MODE), value 0'
    #event_dock='*code 1 (SW_TABLET_MODE), value *'
    evtest "$device" | while read line; do
      case $line in
        #($event_dock) set_displays_external ;;
        ($event_tablet_on) set_displays_external_kbd false ;;
        ($event_tablet_off) set_displays_external_kbd true ;;
        #*) echo $line
      esac
    done
    ;;
  *) echo "Usage: duo <top|bottom|both|set-displays|toggle|status|set-tablet-mapping|bat-limit|sync-backlight|watch-backlight|watch-rotation>"
esac
